spin_version = "1"
authors = ["Adam Reese <adam@reese.io>"]
description = ""
name = "spin-print-request"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-print-request"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
